"""
This type stub file was generated by pyright.
"""

import matplotlib.axes
import matplotlib.figure
import matplotlib.lines
import numpy as np
import logicsponge.core as ls
from collections.abc import Callable
from typing import Self, TypedDict

"""Dashboards for logicsponge."""
logger = ...
class PlotParams(TypedDict):
    """Plot parameters."""
    x: list[float]
    y: list[float]
    args: list
    kwargs: dict
    ...


class Plot(ls.FunctionTerm):
    """Plot data items.

    typical uses are:
    - Plot(x='a', y=['b', 'c'])
    - Plot(x='a', y='b')
    - Plot(y='b') : plot over round number
    - Plot() : plot all keys over round number
    """
    x_name: str
    y_names: list[str] | None
    lines: dict[str, matplotlib.lines.Line2D]
    fig: matplotlib.figure.Figure | None
    ax: matplotlib.axes.Axes | None
    incremental: bool
    def __init__(self, *args, x: str = ..., y: str | list[str] | None = ..., incremental: bool = ..., **kwargs) -> None:
        """Create a Plot object."""
        ...
    
    def plot(self, item: ls.DataItem) -> None:
        """Plot the new item."""
        ...
    
    def add_data(self, item: ls.DataItem) -> None:
        """Add data to the plot."""
        ...
    
    def f(self, item: ls.DataItem) -> ls.DataItem:
        """Run on new data item."""
        ...
    


class DeepPlot(ls.FunctionTerm):
    """A complete, non-iterative plot."""
    fig: matplotlib.figure.Figure | None
    ax: matplotlib.axes.Axes | None
    then_fun: Callable[[Self, ls.DataItem], None] | None
    def __init__(self, *args, **kwargs) -> None:
        """Create a DeepPlot object."""
        ...
    
    def plot(self, params: PlotParams) -> None:
        """Make the plot."""
        ...
    
    def f(self, item: ls.DataItem) -> ls.DataItem:
        """Run f on new data item."""
        ...
    
    def then(self, fun: Callable[[Self, ls.DataItem], None]) -> Self:
        """Run a function after the plotting."""
        ...
    


def is_finite(num: float | np.number) -> bool:
    """Return if num is a finite number."""
    ...

