"""
This type stub file was generated by pyright.
"""

from geopy.geocoders import *
from geopy.location import Location
from geopy.point import Point
from geopy.timezone import Timezone
from geopy.util import __version__, __version_info__, get_version

"""
geopy is a Python client for several popular geocoding web services.

geopy makes it easy for Python developers to locate the coordinates of
addresses, cities, countries, and landmarks across the globe using third-party
geocoders and other data sources.

geopy is tested against CPython (versions 3.7, 3.8, 3.9, 3.10, 3.11)
and PyPy3. geopy 1.x line also supported CPython 2.7, 3.4 and PyPy2.
"""
