"""
This type stub file was generated by pyright.
"""

pytz_available = ...
__all__ = ("Timezone", )
def ensure_pytz_is_installed(): # -> None:
    ...

def from_timezone_name(timezone_name, raw): # -> Timezone:
    ...

def from_fixed_gmt_offset(gmt_offset_hours, raw): # -> Timezone:
    ...

class Timezone:
    """
    Contains a parsed response for a timezone request, which is
    implemented in few geocoders which provide such lookups.
    """
    __slots__ = ...
    def __init__(self, pytz_timezone, raw) -> None:
        ...
    
    @property
    def pytz_timezone(self): # -> Any:
        """
        pytz timezone instance.

        :rtype: :class:`pytz.tzinfo.BaseTzInfo`
        """
        ...
    
    @property
    def raw(self): # -> Any:
        """
        Timezone's raw, unparsed geocoder response. For details on this,
        consult the service's documentation.

        :rtype: dict
        """
        ...
    
    def __str__(self) -> str:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def __getstate__(self): # -> tuple[Any, Any]:
        ...
    
    def __setstate__(self, state): # -> None:
        ...
    
    def __eq__(self, other) -> bool:
        ...
    
    def __ne__(self, other) -> bool:
        ...
    


