"""
This type stub file was generated by pyright.
"""

"""``geopy.units`` module provides utility functions for performing
angle and distance unit conversions.

Some shortly named aliases are provided for convenience (e.g.
:func:`.km` is an alias for :func:`.kilometers`).
"""
def degrees(radians=..., arcminutes=..., arcseconds=...): # -> float:
    """
    Convert angle to degrees.
    """
    ...

def radians(degrees=..., arcminutes=..., arcseconds=...): # -> float:
    """
    Convert angle to radians.
    """
    ...

def arcminutes(degrees=..., radians=..., arcseconds=...): # -> float:
    """
    Convert angle to arcminutes.
    """
    ...

def arcseconds(degrees=..., radians=..., arcminutes=...):
    """
    Convert angle to arcseconds.
    """
    ...

def kilometers(meters=..., miles=..., feet=..., nautical=...): # -> float:
    """
    Convert distance to kilometers.
    """
    ...

def meters(kilometers=..., miles=..., feet=..., nautical=...): # -> float:
    """
    Convert distance to meters.
    """
    ...

def miles(kilometers=..., meters=..., feet=..., nautical=...): # -> float:
    """
    Convert distance to miles.
    """
    ...

def feet(kilometers=..., meters=..., miles=..., nautical=...): # -> float:
    """
    Convert distance to feet.
    """
    ...

def nautical(kilometers=..., meters=..., miles=..., feet=...): # -> float:
    """
    Convert distance to nautical miles.
    """
    ...

rad = ...
arcmin = ...
arcsec = ...
km = ...
m = ...
mi = ...
ft = ...
nm = ...
